pipeline {
  agent any

  environment {
    IMAGE_NAME = "nikhilsonawane/devops-app"
    KUBECONFIG_CRED = credentials('kubeconfig-jenkins')
  }

  stages {

    stage('Build Image') {
      steps {
        sh """
        docker build -t $IMAGE_NAME:${BUILD_NUMBER} app
        """
      }
    }

    stage('Push Image') {
      steps {
        sh """
        docker push $IMAGE_NAME:${BUILD_NUMBER}
        """
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        withEnv(["KUBECONFIG=$KUBECONFIG_CRED"]) {
          sh """
          kubectl apply -f k8s/
          kubectl rollout status deployment/devops-app
          """
        }
      }
    }
  }

  post {
    failure {
      echo "Pipeline failed"
    }
  }
}
